#!/usr/bin/env bash
# =============================================================================
# Generate Rules Script
# =============================================================================
# This script generates alert and recording rules from community mixins.
# It follows the kube-prometheus-stack pattern of generating rules that
# are then embedded in the chart templates.
#
# The generated rules are placed in templates/rules/ directory as Helm templates.
#
# Usage: ./hack/generate-rules.sh
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
MIXINS_DIR="${ROOT_DIR}/mixins"
RULES_OUTPUT_DIR="${ROOT_DIR}/templates/rules"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check dependencies
check_dependencies() {
    log_info "Checking dependencies..."
    
    local missing=0
    
    if ! command -v jsonnet &> /dev/null; then
        log_error "jsonnet is not installed."
        log_info "Install: go install github.com/google/go-jsonnet/cmd/jsonnet@latest"
        missing=1
    fi
    
    if ! command -v jq &> /dev/null; then
        log_error "jq is not installed."
        missing=1
    fi
    
    if [[ $missing -eq 1 ]]; then
        exit 1
    fi
    
    log_info "All dependencies found."
}

# Create output directories
setup_directories() {
    log_info "Setting up directories..."
    mkdir -p "${RULES_OUTPUT_DIR}"
}

# Generate the rules jsonnet file
create_rules_jsonnet() {
    log_info "Creating rules jsonnet..."
    
    cat > "${MIXINS_DIR}/rules.jsonnet" << 'JSONNET_EOF'
// Rules generation from mixins
// This file is used by hack/generate-rules.sh

local config = import 'config.libsonnet';

// Import mixins if they exist
local kubernetesMixin = (import 'kubernetes-mixin/mixin.libsonnet') + {
  _config+:: config._config,
};

local nodeMixin = (import 'node-mixin/mixin.libsonnet') + {
  _config+:: config._config,
};

// Output structure
{
  // Prometheus/VMRule compatible format
  prometheusRules: kubernetesMixin.prometheusRules,
  prometheusAlerts: kubernetesMixin.prometheusAlerts,
  nodeRules: nodeMixin.prometheusRules,
  nodeAlerts: nodeMixin.prometheusAlerts,
}
JSONNET_EOF
}

# Generate Kubernetes alert rules
generate_kubernetes_alerts() {
    log_info "Generating Kubernetes alert rules..."
    
    if [[ ! -d "${MIXINS_DIR}/vendor/kubernetes-mixin" ]]; then
        log_warn "kubernetes-mixin not found in vendor. Skipping Kubernetes alerts."
        log_info "Run 'make mixins-install' first to download mixins."
        return
    fi
    
    cd "${MIXINS_DIR}"
    
    # Generate alerts
    cat > k8s-alerts.jsonnet << 'EOF'
local kubernetes = import 'kubernetes-mixin/mixin.libsonnet';
local config = import 'config.libsonnet';

kubernetes {
  _config+:: config._config,
}.prometheusAlerts
EOF

    local output_file="${RULES_OUTPUT_DIR}/kubernetes-alerts.yaml"
    
    # Generate and convert to Helm template
    cat > "${output_file}" << 'HELM_HEADER'
{{- if and .Values.mixins.enabled .Values.mixins.kubernetes.alerts }}
# =============================================================================
# Kubernetes Alert Rules
# =============================================================================
# GENERATED FILE - DO NOT EDIT
# Generated by: hack/generate-rules.sh
# Source: kubernetes-mixin
#
# To regenerate, run: make generate-rules
# =============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-observability-stack.fullname" . }}-kubernetes-alerts
  namespace: {{ include "k8s-observability-stack.namespace" . }}
  labels:
    {{- include "k8s-observability-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: alerting-rules
data:
  kubernetes-alerts.yaml: |
HELM_HEADER

    # Try to generate rules, or use placeholder
    if jsonnet -J vendor k8s-alerts.jsonnet 2>/dev/null | jq -r 'to_entries[] | "    \(.key): \(.value | @json)"' >> "${output_file}" 2>/dev/null; then
        log_info "  Generated Kubernetes alerts."
    else
        # If generation fails, add placeholder content
        cat >> "${output_file}" << 'PLACEHOLDER'
    groups:
      - name: kubernetes.alerts.placeholder
        rules:
          - alert: KubernetesAlertPlaceholder
            annotations:
              description: 'This is a placeholder alert. Run make sync-mixins to generate real alerts.'
              summary: Placeholder alert rule
            expr: 'vector(0) == 1'
            labels:
              severity: none
PLACEHOLDER
        log_warn "  Using placeholder for Kubernetes alerts. Run 'make sync-mixins' to generate real rules."
    fi
    
    echo '{{- end }}' >> "${output_file}"
    
    rm -f k8s-alerts.jsonnet
}

# Generate Kubernetes recording rules
generate_kubernetes_rules() {
    log_info "Generating Kubernetes recording rules..."
    
    if [[ ! -d "${MIXINS_DIR}/vendor/kubernetes-mixin" ]]; then
        log_warn "kubernetes-mixin not found. Skipping Kubernetes rules."
        return
    fi
    
    cd "${MIXINS_DIR}"
    
    cat > k8s-rules.jsonnet << 'EOF'
local kubernetes = import 'kubernetes-mixin/mixin.libsonnet';
local config = import 'config.libsonnet';

kubernetes {
  _config+:: config._config,
}.prometheusRules
EOF

    local output_file="${RULES_OUTPUT_DIR}/kubernetes-rules.yaml"
    
    cat > "${output_file}" << 'HELM_HEADER'
{{- if and .Values.mixins.enabled .Values.mixins.kubernetes.enabled }}
# =============================================================================
# Kubernetes Recording Rules
# =============================================================================
# GENERATED FILE - DO NOT EDIT
# Generated by: hack/generate-rules.sh
# Source: kubernetes-mixin
# =============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-observability-stack.fullname" . }}-kubernetes-rules
  namespace: {{ include "k8s-observability-stack.namespace" . }}
  labels:
    {{- include "k8s-observability-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: recording-rules
data:
  kubernetes-rules.yaml: |
HELM_HEADER

    if jsonnet -J vendor k8s-rules.jsonnet 2>/dev/null | jq -r 'to_entries[] | "    \(.key): \(.value | @json)"' >> "${output_file}" 2>/dev/null; then
        log_info "  Generated Kubernetes recording rules."
    else
        cat >> "${output_file}" << 'PLACEHOLDER'
    groups: []
PLACEHOLDER
        log_warn "  Using empty placeholder for Kubernetes rules."
    fi
    
    echo '{{- end }}' >> "${output_file}"
    
    rm -f k8s-rules.jsonnet
}

# Generate Node exporter alerts
generate_node_alerts() {
    log_info "Generating Node exporter alert rules..."
    
    if [[ ! -d "${MIXINS_DIR}/vendor/node-mixin" ]]; then
        log_warn "node-mixin not found. Skipping Node alerts."
        return
    fi
    
    cd "${MIXINS_DIR}"
    
    cat > node-alerts.jsonnet << 'EOF'
local node = import 'node-mixin/mixin.libsonnet';
local config = import 'config.libsonnet';

node {
  _config+:: config._config,
}.prometheusAlerts
EOF

    local output_file="${RULES_OUTPUT_DIR}/node-alerts.yaml"
    
    cat > "${output_file}" << 'HELM_HEADER'
{{- if and .Values.mixins.enabled .Values.mixins.nodeExporter.alerts }}
# =============================================================================
# Node Exporter Alert Rules
# =============================================================================
# GENERATED FILE - DO NOT EDIT
# Generated by: hack/generate-rules.sh
# Source: node-mixin
# =============================================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-observability-stack.fullname" . }}-node-alerts
  namespace: {{ include "k8s-observability-stack.namespace" . }}
  labels:
    {{- include "k8s-observability-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: alerting-rules
data:
  node-alerts.yaml: |
HELM_HEADER

    if jsonnet -J vendor node-alerts.jsonnet 2>/dev/null | jq -r 'to_entries[] | "    \(.key): \(.value | @json)"' >> "${output_file}" 2>/dev/null; then
        log_info "  Generated Node alerts."
    else
        cat >> "${output_file}" << 'PLACEHOLDER'
    groups:
      - name: node.alerts.placeholder
        rules: []
PLACEHOLDER
        log_warn "  Using empty placeholder for Node alerts."
    fi
    
    echo '{{- end }}' >> "${output_file}"
    
    rm -f node-alerts.jsonnet
}

# Create placeholder rules when mixins aren't available
create_placeholder_rules() {
    log_info "Creating placeholder rule templates..."
    
    # Kubernetes alerts placeholder
    if [[ ! -f "${RULES_OUTPUT_DIR}/kubernetes-alerts.yaml" ]]; then
        cat > "${RULES_OUTPUT_DIR}/kubernetes-alerts.yaml" << 'EOF'
{{- if and .Values.mixins.enabled .Values.mixins.kubernetes.alerts }}
# Kubernetes Alert Rules - Placeholder
# Run 'make sync-mixins' to generate rules from kubernetes-mixin
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-observability-stack.fullname" . }}-kubernetes-alerts
  namespace: {{ include "k8s-observability-stack.namespace" . }}
  labels:
    {{- include "k8s-observability-stack.labels" . | nindent 4 }}
data:
  alerts.yaml: |
    groups: []
{{- end }}
EOF
    fi
    
    # Kubernetes rules placeholder
    if [[ ! -f "${RULES_OUTPUT_DIR}/kubernetes-rules.yaml" ]]; then
        cat > "${RULES_OUTPUT_DIR}/kubernetes-rules.yaml" << 'EOF'
{{- if and .Values.mixins.enabled .Values.mixins.kubernetes.enabled }}
# Kubernetes Recording Rules - Placeholder
# Run 'make sync-mixins' to generate rules from kubernetes-mixin
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-observability-stack.fullname" . }}-kubernetes-rules
  namespace: {{ include "k8s-observability-stack.namespace" . }}
  labels:
    {{- include "k8s-observability-stack.labels" . | nindent 4 }}
data:
  rules.yaml: |
    groups: []
{{- end }}
EOF
    fi
    
    # Node alerts placeholder
    if [[ ! -f "${RULES_OUTPUT_DIR}/node-alerts.yaml" ]]; then
        cat > "${RULES_OUTPUT_DIR}/node-alerts.yaml" << 'EOF'
{{- if and .Values.mixins.enabled .Values.mixins.nodeExporter.alerts }}
# Node Exporter Alert Rules - Placeholder
# Run 'make sync-mixins' to generate rules from node-mixin
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-observability-stack.fullname" . }}-node-alerts
  namespace: {{ include "k8s-observability-stack.namespace" . }}
  labels:
    {{- include "k8s-observability-stack.labels" . | nindent 4 }}
data:
  alerts.yaml: |
    groups: []
{{- end }}
EOF
    fi
}

# Main execution
main() {
    log_info "Starting rules generation..."
    
    check_dependencies
    setup_directories
    
    # Check if mixins are installed
    if [[ -d "${MIXINS_DIR}/vendor" ]]; then
        create_rules_jsonnet
        generate_kubernetes_alerts
        generate_kubernetes_rules
        generate_node_alerts
    else
        log_warn "Mixin vendor directory not found."
        log_info "Creating placeholder templates. Run 'make sync-mixins' to generate real rules."
        create_placeholder_rules
    fi
    
    log_info ""
    log_info "Rules generation completed!"
    log_info "Output directory: ${RULES_OUTPUT_DIR}"
}

main "$@"
